const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "256774856806"
const SESSION_ID = "PRABATH-MD~E21i2SJD#vGBk7ZEm64aRFm-nluEzpky2kVZbvUBwIjFLDNrCqis"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
